
#	Connector: Sales Cloud:

sed -i 's/@ICS_CONNECTOR_SC_URI@/${ICS_CONNECTOR_SC_URI}/g' ${ICS_CONNECTOR_SC_CONFIG_NAME}
sed -i 's/@ICS_CONNECTOR_SC_OSC_SERVICE_CATALOG_WSDL_URL@/${ICS_CONNECTOR_SC_OSC_SERVICE_CATALOG_WSDL_URL}/g' ${ICS_CONNECTOR_SC_CONFIG_NAME}
sed -i 's/@ICS_CONNECTOR_SC_OSC_EVENTS_CATALOG_WSDL_URL@/${ICS_CONNECTOR_SC_OSC_EVENTS_CATALOG_WSDL_URL}/g' ${ICS_CONNECTOR_SC_CONFIG_NAME}
sed -i 's/@ICS_CONNECTOR_SC_USERNAME@/${ICS_CONNECTOR_SC_USERNAME}/g' ${ICS_CONNECTOR_SC_CONFIG_NAME}
sed -i 's/@ICS_CONNECTOR_SC_PASSWORD@/${ICS_CONNECTOR_SC_PASSWORD}/g' ${ICS_CONNECTOR_SC_CONFIG_NAME}


#	Connector: SalesForce:

sed -i 's/@ICS_CONNECTOR_SF_URI@/${ICS_CONNECTOR_SF_URI}/g' ${ICS_CONNECTOR_SF_CONFIG_NAME}
sed -i 's/@ICS_CONNECTOR_SF_USERNAME@/${ICS_CONNECTOR_SF_USERNAME}/g' ${ICS_CONNECTOR_SF_CONFIG_NAME}
sed -i 's/@ICS_CONNECTOR_SF_PASSWORD@/${ICS_CONNECTOR_SF_PASSWORD}/g' ${ICS_CONNECTOR_SF_CONFIG_NAME}
